# Generated by Django 5.2.9 on 2025-12-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanfic',
            name='comentarios',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fanfic',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
