# Generated by Django 5.2.9 on 2025-12-08 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0003_alter_fanfic_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fanfic',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='fanfic',
            name='fandom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='autor',
            field=models.CharField(max_length=100),
        ),
    ]
