# Generated by Django 5.2.9 on 2025-12-08 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0004_remove_fanfic_comentarios_fanfic_fandom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fanfic',
            name='traducao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
