# Generated by Django 5.2.9 on 2025-12-27 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0005_fanfic_traducao_alter_fanfic_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='fanfic',
            name='fandom',
        ),
        migrations.RemoveField(
            model_name='fanfic',
            name='traducao',
        ),
        migrations.AddField(
            model_name='fanfic',
            name='status',
            field=models.CharField(choices=[('completa', 'Completa'), ('andamento', 'Em andamento')], default='andamento', max_length=20),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fanfic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='fanfics.fanfic')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=150)),
                ('texto', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fanfic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='fanfics.fanfic')),
            ],
        ),
        migrations.AddField(
            model_name='fanfic',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='fanfics', to='fanfics.tag'),
        ),
    ]
