# Generated by Django 5.2.9 on 2025-12-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0006_tag_remove_fanfic_fandom_remove_fanfic_traducao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitulo',
            options={'ordering': ['ordem']},
        ),
        migrations.RenameField(
            model_name='capitulo',
            old_name='conteudo',
            new_name='texto',
        ),
        migrations.AddField(
            model_name='capitulo',
            name='ordem',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='capitulo',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
