# Generated by Django 5.2.9 on 2025-12-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0008_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
