# Generated by Django 5.2.9 on 2026-01-05 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0009_delete_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitulo',
            options={},
        ),
        migrations.RenameField(
            model_name='capitulo',
            old_name='texto',
            new_name='conteudo',
        ),
        migrations.RemoveField(
            model_name='capitulo',
            name='ordem',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fanfics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='status',
            field=models.CharField(choices=[('andamento', 'Em andamento'), ('completa', 'Completa')], default='andamento', max_length=20),
        ),
        migrations.AlterField(
            model_name='fanfic',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
