# Generated by Django 5.2.9 on 2026-01-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0012_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitulo',
            options={'ordering': ['ordem']},
        ),
        migrations.AddField(
            model_name='capitulo',
            name='ordem',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
