# Generated by Django 5.2.9 on 2026-01-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0013_alter_capitulo_options_capitulo_ordem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fanfic',
            old_name='status',
            new_name='estado',
        ),
        migrations.AddField(
            model_name='fanfic',
            name='visibilidade',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], default='draft', max_length=10),
        ),
    ]
