# Generated by Django 5.2.9 on 2026-01-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fanfics', '0014_rename_status_fanfic_estado_fanfic_visibilidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitulo',
            options={},
        ),
    ]
